//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.business.Enums {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class LibellesEnums {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal LibellesEnums() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.business.Enums.LibellesEnums", typeof(LibellesEnums).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Remplissage des groupes.
		/// </summary>
		internal static string Graph_RemplissageGroupes {
			get {
				return ResourceManager.GetString("Graph_RemplissageGroupes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition des adhérents par ville.
		/// </summary>
		internal static string Graph_RepartitionAdherentsVilles {
			get {
				return ResourceManager.GetString("Graph_RepartitionAdherentsVilles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition H/F.
		/// </summary>
		internal static string Graph_RepartitionHommesFemmes {
			get {
				return ResourceManager.GetString("Graph_RepartitionHommesFemmes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition licenciés/non licenciés.
		/// </summary>
		internal static string Graph_RepartitionLicencies {
			get {
				return ResourceManager.GetString("Graph_RepartitionLicencies", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition majeurs/mineurs.
		/// </summary>
		internal static string Graph_RepartitionMajeursMineurs {
			get {
				return ResourceManager.GetString("Graph_RepartitionMajeursMineurs", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition résidents/extérieurs.
		/// </summary>
		internal static string Graph_RepartitionResidentsExterieurs {
			get {
				return ResourceManager.GetString("Graph_RepartitionResidentsExterieurs", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition des adhérents par section.
		/// </summary>
		internal static string Graph_RepartitionSections {
			get {
				return ResourceManager.GetString("Graph_RepartitionSections", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à &lt;LIBELLE ABSENT&gt;.
		/// </summary>
		internal static string LibelleAbsent {
			get {
				return ResourceManager.GetString("LibelleAbsent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Certificats médicaux manquants.
		/// </summary>
		internal static string Report_CertificatsManquants {
			get {
				return ResourceManager.GetString("Report_CertificatsManquants", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Aucun rapport n&apos;a été généré - Code rapport inconnu.
		/// </summary>
		internal static string Report_ErrGenerationCodeInconnu {
			get {
				return ResourceManager.GetString("Report_ErrGenerationCodeInconnu", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Inventaire complet.
		/// </summary>
		internal static string Report_InventaireCompletEquipementExcel {
			get {
				return ResourceManager.GetString("Report_InventaireCompletEquipementExcel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Inventaire simple.
		/// </summary>
		internal static string Report_InventaireSimpleEquipementExcel {
			get {
				return ResourceManager.GetString("Report_InventaireSimpleEquipementExcel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Liste des adhérents.
		/// </summary>
		internal static string Report_ListeAdherents {
			get {
				return ResourceManager.GetString("Report_ListeAdherents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition des adhérents par âge/sexe/ville.
		/// </summary>
		internal static string Report_RepartitionAdherentsAge {
			get {
				return ResourceManager.GetString("Report_RepartitionAdherentsAge", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition des adhérents par âge/licence/ville.
		/// </summary>
		internal static string Report_RepartitionAdherentsAgeLicenceVille {
			get {
				return ResourceManager.GetString("Report_RepartitionAdherentsAgeLicenceVille", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Répartition des adhérents par groupe.
		/// </summary>
		internal static string Report_RepartitionAdherentsGroupes {
			get {
				return ResourceManager.GetString("Report_RepartitionAdherentsGroupes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Exports.
		/// </summary>
		internal static string UC_Backup {
			get {
				return ResourceManager.GetString("UC_Backup", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Groupes.
		/// </summary>
		internal static string UC_ConsultationGroupes {
			get {
				return ResourceManager.GetString("UC_ConsultationGroupes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Sections.
		/// </summary>
		internal static string UC_ConsultationSections {
			get {
				return ResourceManager.GetString("UC_ConsultationSections", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Rapports.
		/// </summary>
		internal static string UC_EcranReporting {
			get {
				return ResourceManager.GetString("UC_EcranReporting", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Graphiques.
		/// </summary>
		internal static string UC_EcranStatistiques {
			get {
				return ResourceManager.GetString("UC_EcranStatistiques", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Groupe.
		/// </summary>
		internal static string UC_FormulaireGroupe {
			get {
				return ResourceManager.GetString("UC_FormulaireGroupe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Section.
		/// </summary>
		internal static string UC_FormulaireSection {
			get {
				return ResourceManager.GetString("UC_FormulaireSection", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des adhérents
		///.
		/// </summary>
		internal static string UC_GestionAdherents {
			get {
				return ResourceManager.GetString("UC_GestionAdherents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des campagnes de vérification.
		/// </summary>
		internal static string UC_GestionCampagnesVerification {
			get {
				return ResourceManager.GetString("UC_GestionCampagnesVerification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des catégories.
		/// </summary>
		internal static string UC_GestionCategories {
			get {
				return ResourceManager.GetString("UC_GestionCategories", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des durées de vie.
		/// </summary>
		internal static string UC_GestionDureesDeVie {
			get {
				return ResourceManager.GetString("UC_GestionDureesDeVie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des équipements.
		/// </summary>
		internal static string UC_GestionEquipements {
			get {
				return ResourceManager.GetString("UC_GestionEquipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des groupes pour la saison courante.
		/// </summary>
		internal static string UC_GestionGroupes {
			get {
				return ResourceManager.GetString("UC_GestionGroupes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Information du club.
		/// </summary>
		internal static string UC_GestionInfosClub {
			get {
				return ResourceManager.GetString("UC_GestionInfosClub", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des inscriptions pour la saison courante.
		/// </summary>
		internal static string UC_GestionInscriptions {
			get {
				return ResourceManager.GetString("UC_GestionInscriptions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des localisations.
		/// </summary>
		internal static string UC_GestionLocalisations {
			get {
				return ResourceManager.GetString("UC_GestionLocalisations", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion de la localisation des équipements.
		/// </summary>
		internal static string UC_GestionLocalisationsEquipements {
			get {
				return ResourceManager.GetString("UC_GestionLocalisationsEquipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des marques.
		/// </summary>
		internal static string UC_GestionMarques {
			get {
				return ResourceManager.GetString("UC_GestionMarques", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des modèles.
		/// </summary>
		internal static string UC_GestionModeles {
			get {
				return ResourceManager.GetString("UC_GestionModeles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Saisie des vérifications.
		/// </summary>
		internal static string UC_GestionSaisiesVerifications {
			get {
				return ResourceManager.GetString("UC_GestionSaisiesVerifications", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des saisons.
		/// </summary>
		internal static string UC_GestionSaisons {
			get {
				return ResourceManager.GetString("UC_GestionSaisons", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des sections.
		/// </summary>
		internal static string UC_GestionSections {
			get {
				return ResourceManager.GetString("UC_GestionSections", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des tranches d&apos;âge.
		/// </summary>
		internal static string UC_GestionTranchesAge {
			get {
				return ResourceManager.GetString("UC_GestionTranchesAge", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des villes.
		/// </summary>
		internal static string UC_GestionVilles {
			get {
				return ResourceManager.GetString("UC_GestionVilles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Initialisation de la base de données.
		/// </summary>
		internal static string UC_InitialisationDatabase {
			get {
				return ResourceManager.GetString("UC_InitialisationDatabase", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Démarrage.
		/// </summary>
		internal static string UC_MainScreenCheck {
			get {
				return ResourceManager.GetString("UC_MainScreenCheck", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nettoyage CNIL.
		/// </summary>
		internal static string UC_NettoyageCNIL {
			get {
				return ResourceManager.GetString("UC_NettoyageCNIL", resourceCulture);
			}
		}
	}
}
