//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.business.ViewModel {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ResCommon {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ResCommon() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.business.ViewModel.ResCommon", typeof(ResCommon).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à gestadh45.sdf.
		/// </summary>
		internal static string DefaultBddName {
			get {
				return ResourceManager.GetString("DefaultBddName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Un élément ayant les mêmes valeurs existe déjà..
		/// </summary>
		internal static string Err_ElementExists {
			get {
				return ResourceManager.GetString("Err_ElementExists", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à .sdf.
		/// </summary>
		internal static string ExtensionBddSqlCe {
			get {
				return ResourceManager.GetString("ExtensionBddSqlCe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à .xlsx.
		/// </summary>
		internal static string ExtensionExcel {
			get {
				return ResourceManager.GetString("ExtensionExcel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Les données suivantes ont été copiées dans le presse papier : 
		///{0}.
		/// </summary>
		internal static string InfoCopiePressePapier {
			get {
				return ResourceManager.GetString("InfoCopiePressePapier", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Les documents ont été générés ({0} fichiers) : {1}.
		/// </summary>
		internal static string InfoDocumentsGeneres {
			get {
				return ResourceManager.GetString("InfoDocumentsGeneres", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à {0} supprimé(e).
		/// </summary>
		internal static string InfoElementSupprime {
			get {
				return ResourceManager.GetString("InfoElementSupprime", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Le rapport &quot;{0}&quot; a été généré.
		/// </summary>
		internal static string InfoRapportGenere {
			get {
				return ResourceManager.GetString("InfoRapportGenere", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Le document a été généré (1 fichier) : {0}.
		/// </summary>
		internal static string InfosDocumentGenere {
			get {
				return ResourceManager.GetString("InfosDocumentGenere", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à La VCard é été générée (1 fichier) : {0}.
		/// </summary>
		internal static string InfosVCardGeneree {
			get {
				return ResourceManager.GetString("InfosVCardGeneree", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Les VCards ont été générées ({0} fichiers) : {1}.
		/// </summary>
		internal static string InfosVCardsGenerees {
			get {
				return ResourceManager.GetString("InfosVCardsGenerees", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à FlagOpenLastDb.
		/// </summary>
		internal static string Setting_FlagOpenLastDb {
			get {
				return ResourceManager.GetString("Setting_FlagOpenLastDb", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à UserConnectionString.
		/// </summary>
		internal static string Setting_UserConnectionString {
			get {
				return ResourceManager.GetString("Setting_UserConnectionString", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à {0} ajouté.
		/// </summary>
		internal static string TemplateAddItemNotification {
			get {
				return ResourceManager.GetString("TemplateAddItemNotification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Copie de {0}.
		/// </summary>
		internal static string TemplateCloneItemComment {
			get {
				return ResourceManager.GetString("TemplateCloneItemComment", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à {0} (Copie).
		/// </summary>
		internal static string TemplateCloneItemName {
			get {
				return ResourceManager.GetString("TemplateCloneItemName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à {0} dupliqué en {1}.
		/// </summary>
		internal static string TemplateCloneNotification {
			get {
				return ResourceManager.GetString("TemplateCloneNotification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à {0} enregistré.
		/// </summary>
		internal static string TemplateSaveItemNotification {
			get {
				return ResourceManager.GetString("TemplateSaveItemNotification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Data Source={0}; Persist Security Info=False;.
		/// </summary>
		internal static string TemplateSqlCeConnectionString {
			get {
				return ResourceManager.GetString("TemplateSqlCeConnectionString", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Confirmation.
		/// </summary>
		internal static string TitreConfirmation {
			get {
				return ResourceManager.GetString("TitreConfirmation", resourceCulture);
			}
		}
	}
}
