//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.services.Documents.Templates {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDocuments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDocuments() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.services.Documents.Templates.ResDocuments", typeof(ResDocuments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attestation - {0}.pdf.
        /// </summary>
        public static string AttestationPDFFileName {
            get {
                return ResourceManager.GetString("AttestationPDFFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .pdf.
        /// </summary>
        public static string ExtensionPDF {
            get {
                return ResourceManager.GetString("ExtensionPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription - {0}.pdf.
        /// </summary>
        public static string InscriptionPDFFileName {
            get {
                return ResourceManager.GetString("InscriptionPDFFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} - {2}.
        /// </summary>
        public static string LibelleAdresse {
            get {
                return ResourceManager.GetString("LibelleAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.
        /// </summary>
        public static string LibelleAdresseClub {
            get {
                return ResourceManager.GetString("LibelleAdresseClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autorisation parentale pour les mineurs.
        /// </summary>
        public static string LibelleAutorisationParentale {
            get {
                return ResourceManager.GetString("LibelleAutorisationParentale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} - {1}.
        /// </summary>
        public static string LibelleCodePostalVilleClub {
            get {
                return ResourceManager.GetString("LibelleCodePostalVilleClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cotisation : {0} euros.
        /// </summary>
        public static string LibelleCotisation {
            get {
                return ResourceManager.GetString("LibelleCotisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fait à {0} le {1}.
        /// </summary>
        public static string LibelleFaitALe {
            get {
                return ResourceManager.GetString("LibelleFaitALe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fait à .............................. le ...............................
        /// </summary>
        public static string LibelleFaitALeVide {
            get {
                return ResourceManager.GetString("LibelleFaitALeVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe : {0}.
        /// </summary>
        public static string LibelleGroupe {
            get {
                return ResourceManager.GetString("LibelleGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail : {0}.
        /// </summary>
        public static string LibelleMailClub {
            get {
                return ResourceManager.GetString("LibelleMailClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence : {0} euros.
        /// </summary>
        public static string LibelleMontantLicence {
            get {
                return ResourceManager.GetString("LibelleMontantLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total : {0} euros.
        /// </summary>
        public static string LibelleMontantTotal {
            get {
                return ResourceManager.GetString("LibelleMontantTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Né(e) le {0}.
        /// </summary>
        public static string LibelleNeLe {
            get {
                return ResourceManager.GetString("LibelleNeLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1}.
        /// </summary>
        public static string LibelleNomAdherent {
            get {
                return ResourceManager.GetString("LibelleNomAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} - Saison {1}.
        /// </summary>
        public static string LibelleNomClubSaison {
            get {
                return ResourceManager.GetString("LibelleNomClubSaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° {0}.
        /// </summary>
        public static string LibelleNumeroClub {
            get {
                return ResourceManager.GetString("LibelleNumeroClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reçu pour l&apos;adhésion {0} à {1}.
        /// </summary>
        public static string LibelleRecuPourAdhesion {
            get {
                return ResourceManager.GetString("LibelleRecuPourAdhesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Section : {0}.
        /// </summary>
        public static string LibelleSection {
            get {
                return ResourceManager.GetString("LibelleSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature de l&apos;adhérent ou de son représentant légal.
        /// </summary>
        public static string LibelleSignatureAdherent {
            get {
                return ResourceManager.GetString("LibelleSignatureAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        public static string LibelleSignatureParents {
            get {
                return ResourceManager.GetString("LibelleSignatureParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIRET : {0}.
        /// </summary>
        public static string LibelleSiret {
            get {
                return ResourceManager.GetString("LibelleSiret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web : {0}.
        /// </summary>
        public static string LibelleSiteWebClub {
            get {
                return ResourceManager.GetString("LibelleSiteWebClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tel. : {0}.
        /// </summary>
        public static string LibelleTelephone {
            get {
                return ResourceManager.GetString("LibelleTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} - {1}.
        /// </summary>
        public static string LibelleTelMail {
            get {
                return ResourceManager.GetString("LibelleTelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription {0} à {1}.
        /// </summary>
        public static string LibelleTitreFicheInscription {
            get {
                return ResourceManager.GetString("LibelleTitreFicheInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à __________________________________________________.
        /// </summary>
        public static string Separateur {
            get {
                return ResourceManager.GetString("Separateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je, soussigné .................................................., agissant en qualité de parent ou de tuteur légal de l&apos;enfant désigné ci-dessus, autorise le club à faire transporter mon enfant au centre hospitalier le plus proche si son état le nécessite ou a prendre toutes les mesures nécessaires en cas d&apos;accident survenant lors de la pratique de l&apos;escalade dans le cadre du club..
        /// </summary>
        public static string TexteAutorisationParentale {
            get {
                return ResourceManager.GetString("TexteAutorisationParentale", resourceCulture);
            }
        }
    }
}
