//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.business.ViewModel.AdherentsVM {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ResAdherents {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ResAdherents() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.business.ViewModel.AdherentsVM.ResAdherents", typeof(ResAdherents).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Adresse.
		/// </summary>
		internal static string DefautAdresse {
			get {
				return ResourceManager.GetString("DefautAdresse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à AAAA.
		/// </summary>
		internal static string DefautNom {
			get {
				return ResourceManager.GetString("DefautNom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Aaaa.
		/// </summary>
		internal static string DefautPrenom {
			get {
				return ResourceManager.GetString("DefautPrenom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Cet adhérent existe déjà.
		/// </summary>
		internal static string ErrAdherentExiste {
			get {
				return ResourceManager.GetString("ErrAdherentExiste", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à L&apos;adresse est obligatoire.
		/// </summary>
		internal static string ErrAdresseObligatoire {
			get {
				return ResourceManager.GetString("ErrAdresseObligatoire", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à La date de naissance est obligatoire.
		/// </summary>
		internal static string ErrDateNaissanceObligatoire {
			get {
				return ResourceManager.GetString("ErrDateNaissanceObligatoire", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Le nom est obligatoire.
		/// </summary>
		internal static string ErrNomObligatoire {
			get {
				return ResourceManager.GetString("ErrNomObligatoire", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Le prénom est obligatoire.
		/// </summary>
		internal static string ErrPrenomObligatoire {
			get {
				return ResourceManager.GetString("ErrPrenomObligatoire", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à La ville est obligatoire.
		/// </summary>
		internal static string ErrVilleObligatoire {
			get {
				return ResourceManager.GetString("ErrVilleObligatoire", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à L&apos;adhérent a été dupliqué.
		/// </summary>
		internal static string InfosAdherentDuplique {
			get {
				return ResourceManager.GetString("InfosAdherentDuplique", resourceCulture);
			}
		}
	}
}
