//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.services.Reporting.Templates {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ResReports {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ResReports() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.services.Reporting.Templates.ResReports", typeof(ResReports).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Catégorie.
		/// </summary>
		public static string HeaderCategorie {
			get {
				return ResourceManager.GetString("HeaderCategorie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Date.
		/// </summary>
		public static string HeaderDate {
			get {
				return ResourceManager.GetString("HeaderDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Date d&apos;achat.
		/// </summary>
		public static string HeaderDateAchat {
			get {
				return ResourceManager.GetString("HeaderDateAchat", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Dernière vérification.
		/// </summary>
		public static string HeaderDateDerniereVerification {
			get {
				return ResourceManager.GetString("HeaderDateDerniereVerification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Date de naissance.
		/// </summary>
		public static string HeaderDateNaissance {
			get {
				return ResourceManager.GetString("HeaderDateNaissance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Email.
		/// </summary>
		public static string HeaderEmail {
			get {
				return ResourceManager.GetString("HeaderEmail", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Evénement.
		/// </summary>
		public static string HeaderEvenement {
			get {
				return ResourceManager.GetString("HeaderEvenement", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Extérieurs licenciés.
		/// </summary>
		public static string HeaderExterieurLicencie {
			get {
				return ResourceManager.GetString("HeaderExterieurLicencie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Extérieurs non licenciés.
		/// </summary>
		public static string HeaderExterieurNonLicencie {
			get {
				return ResourceManager.GetString("HeaderExterieurNonLicencie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Extérieurs (F).
		/// </summary>
		public static string HeaderFemmesExterieur {
			get {
				return ResourceManager.GetString("HeaderFemmesExterieur", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Résidents (F).
		/// </summary>
		public static string HeaderFemmesResident {
			get {
				return ResourceManager.GetString("HeaderFemmesResident", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Groupe.
		/// </summary>
		public static string HeaderGroupe {
			get {
				return ResourceManager.GetString("HeaderGroupe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Extérieurs (H).
		/// </summary>
		public static string HeaderHommesExterieur {
			get {
				return ResourceManager.GetString("HeaderHommesExterieur", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Résidents (H).
		/// </summary>
		public static string HeaderHommesResident {
			get {
				return ResourceManager.GetString("HeaderHommesResident", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Tranche d&apos;âge.
		/// </summary>
		public static string HeaderLibelle {
			get {
				return ResourceManager.GetString("HeaderLibelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Localisation.
		/// </summary>
		public static string HeaderLocalisation {
			get {
				return ResourceManager.GetString("HeaderLocalisation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Marque.
		/// </summary>
		public static string HeaderMarque {
			get {
				return ResourceManager.GetString("HeaderMarque", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Modèle.
		/// </summary>
		public static string HeaderModele {
			get {
				return ResourceManager.GetString("HeaderModele", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. inscriptions.
		/// </summary>
		public static string HeaderNbInscriptions {
			get {
				return ResourceManager.GetString("HeaderNbInscriptions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. places.
		/// </summary>
		public static string HeaderNbPlaces {
			get {
				return ResourceManager.GetString("HeaderNbPlaces", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. places dispo.
		/// </summary>
		public static string HeaderNbPlacesDispo {
			get {
				return ResourceManager.GetString("HeaderNbPlacesDispo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nom.
		/// </summary>
		public static string HeaderNom {
			get {
				return ResourceManager.GetString("HeaderNom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à N°.
		/// </summary>
		public static string HeaderNumero {
			get {
				return ResourceManager.GetString("HeaderNumero", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Prénom.
		/// </summary>
		public static string HeaderPrenom {
			get {
				return ResourceManager.GetString("HeaderPrenom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Raison.
		/// </summary>
		public static string HeaderRaisonStatutVerification {
			get {
				return ResourceManager.GetString("HeaderRaisonStatutVerification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Résidents licenciés.
		/// </summary>
		public static string HeaderResidentLicencie {
			get {
				return ResourceManager.GetString("HeaderResidentLicencie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Résidents non licenciés.
		/// </summary>
		public static string HeaderResidentNonLicencie {
			get {
				return ResourceManager.GetString("HeaderResidentNonLicencie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Section.
		/// </summary>
		public static string HeaderSection {
			get {
				return ResourceManager.GetString("HeaderSection", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Statut.
		/// </summary>
		public static string HeaderStatutVerification {
			get {
				return ResourceManager.GetString("HeaderStatutVerification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Téléphone.
		/// </summary>
		public static string HeaderTelephone {
			get {
				return ResourceManager.GetString("HeaderTelephone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Total.
		/// </summary>
		public static string HeaderTotal {
			get {
				return ResourceManager.GetString("HeaderTotal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Total extérieurs.
		/// </summary>
		public static string HeaderTotalExterieurs {
			get {
				return ResourceManager.GetString("HeaderTotalExterieurs", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Total licenciés.
		/// </summary>
		public static string HeaderTotalLicencie {
			get {
				return ResourceManager.GetString("HeaderTotalLicencie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Total non licenciés.
		/// </summary>
		public static string HeaderTotalNonLicencie {
			get {
				return ResourceManager.GetString("HeaderTotalNonLicencie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Total résidents.
		/// </summary>
		public static string HeaderTotalresidents {
			get {
				return ResourceManager.GetString("HeaderTotalresidents", resourceCulture);
			}
		}
	}
}
