//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.model {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ResEnums {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ResEnums() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.model.ResEnums", typeof(ResEnums).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Dimanche.
		/// </summary>
		internal static string JourSemaine_Dimanche {
			get {
				return ResourceManager.GetString("JourSemaine_Dimanche", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Jeudi.
		/// </summary>
		internal static string JourSemaine_Jeudi {
			get {
				return ResourceManager.GetString("JourSemaine_Jeudi", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Lundi.
		/// </summary>
		internal static string JourSemaine_Lundi {
			get {
				return ResourceManager.GetString("JourSemaine_Lundi", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Mardi.
		/// </summary>
		internal static string JourSemaine_Mardi {
			get {
				return ResourceManager.GetString("JourSemaine_Mardi", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Mercredi.
		/// </summary>
		internal static string JourSemaine_Mercredi {
			get {
				return ResourceManager.GetString("JourSemaine_Mercredi", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Samedi.
		/// </summary>
		internal static string JourSemaine_Samedi {
			get {
				return ResourceManager.GetString("JourSemaine_Samedi", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Vendredi.
		/// </summary>
		internal static string JourSemaine_Vendredi {
			get {
				return ResourceManager.GetString("JourSemaine_Vendredi", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à &lt;LIBELLE ABSENT&gt;.
		/// </summary>
		internal static string LibelleAbsent {
			get {
				return ResourceManager.GetString("LibelleAbsent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à F.
		/// </summary>
		internal static string Sexe_F {
			get {
				return ResourceManager.GetString("Sexe_F", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à M.
		/// </summary>
		internal static string Sexe_M {
			get {
				return ResourceManager.GetString("Sexe_M", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Annulée.
		/// </summary>
		internal static string StatutInscription_Annulee {
			get {
				return ResourceManager.GetString("StatutInscription_Annulee", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à A suivre.
		/// </summary>
		internal static string StatutInscription_ASuivre {
			get {
				return ResourceManager.GetString("StatutInscription_ASuivre", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Validée.
		/// </summary>
		internal static string StatutInscription_Validee {
			get {
				return ResourceManager.GetString("StatutInscription_Validee", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à A vérifier.
		/// </summary>
		internal static string StatutVerification_AVerifier {
			get {
				return ResourceManager.GetString("StatutVerification_AVerifier", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ok.
		/// </summary>
		internal static string StatutVerification_Ok {
			get {
				return ResourceManager.GetString("StatutVerification_Ok", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Rebut.
		/// </summary>
		internal static string StatutVerification_Rebut {
			get {
				return ResourceManager.GetString("StatutVerification_Rebut", resourceCulture);
			}
		}
	}
}
