//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.wpf.Ressources {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class UI_Labels {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal UI_Labels() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.wpf.Ressources.UI_Labels", typeof(UI_Labels).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Adresse : .
		/// </summary>
		public static string Adherent_Adresse {
			get {
				return ResourceManager.GetString("Adherent_Adresse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Age : .
		/// </summary>
		public static string Adherent_Age {
			get {
				return ResourceManager.GetString("Adherent_Age", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Naissance : .
		/// </summary>
		public static string Adherent_DateNaissance {
			get {
				return ResourceManager.GetString("Adherent_DateNaissance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Mail 1 : .
		/// </summary>
		public static string Adherent_Mail1 {
			get {
				return ResourceManager.GetString("Adherent_Mail1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Mail 2 : .
		/// </summary>
		public static string Adherent_Mail2 {
			get {
				return ResourceManager.GetString("Adherent_Mail2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Mail 3 : .
		/// </summary>
		public static string Adherent_Mail3 {
			get {
				return ResourceManager.GetString("Adherent_Mail3", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. adhérents : .
		/// </summary>
		public static string Adherent_NbAdherents {
			get {
				return ResourceManager.GetString("Adherent_NbAdherents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nom : .
		/// </summary>
		public static string Adherent_Nom {
			get {
				return ResourceManager.GetString("Adherent_Nom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Prénom : .
		/// </summary>
		public static string Adherent_Prenom {
			get {
				return ResourceManager.GetString("Adherent_Prenom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Sexe : .
		/// </summary>
		public static string Adherent_Sexe {
			get {
				return ResourceManager.GetString("Adherent_Sexe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Tél. 1 : .
		/// </summary>
		public static string Adherent_Telephone1 {
			get {
				return ResourceManager.GetString("Adherent_Telephone1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Tél. 2 : .
		/// </summary>
		public static string Adherent_Telephone2 {
			get {
				return ResourceManager.GetString("Adherent_Telephone2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Tél. 3 : .
		/// </summary>
		public static string Adherent_Telephone3 {
			get {
				return ResourceManager.GetString("Adherent_Telephone3", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ville : .
		/// </summary>
		public static string Adherent_Ville {
			get {
				return ResourceManager.GetString("Adherent_Ville", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Créer une nouvelle base.
		/// </summary>
		public static string Btn_CreerBdd {
			get {
				return ResourceManager.GetString("Btn_CreerBdd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ouvrir une base.
		/// </summary>
		public static string Btn_OuvrirBdd {
			get {
				return ResourceManager.GetString("Btn_OuvrirBdd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ouvrir la dernière base.
		/// </summary>
		public static string Btn_OuvrirDerniereBdd {
			get {
				return ResourceManager.GetString("Btn_OuvrirDerniereBdd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Quitter.
		/// </summary>
		public static string Btn_Quitter {
			get {
				return ResourceManager.GetString("Btn_Quitter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Saison courante.
		/// </summary>
		public static string Btn_SaisonCourante {
			get {
				return ResourceManager.GetString("Btn_SaisonCourante", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Section par défaut.
		/// </summary>
		public static string Btn_SectionDefaut {
			get {
				return ResourceManager.GetString("Btn_SectionDefaut", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Libellé : .
		/// </summary>
		public static string Categorie_Libelle {
			get {
				return ResourceManager.GetString("Categorie_Libelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Durée de vie : .
		/// </summary>
		public static string Categories_DureeDeVie {
			get {
				return ResourceManager.GetString("Categories_DureeDeVie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. catégories : .
		/// </summary>
		public static string Categories_NbCategories {
			get {
				return ResourceManager.GetString("Categories_NbCategories", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Libellé : .
		/// </summary>
		public static string DureesDeVie_Libelle {
			get {
				return ResourceManager.GetString("DureesDeVie_Libelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. années : .
		/// </summary>
		public static string DureesDeVie_NbAnnees {
			get {
				return ResourceManager.GetString("DureesDeVie_NbAnnees", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. durées de vie : .
		/// </summary>
		public static string DureesDeVie_NbDureesDeVie {
			get {
				return ResourceManager.GetString("DureesDeVie_NbDureesDeVie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. mois : .
		/// </summary>
		public static string DureesDeVie_NbMois {
			get {
				return ResourceManager.GetString("DureesDeVie_NbMois", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Afficher le matériel au rebut : .
		/// </summary>
		public static string Equipements_AfficherRebut {
			get {
				return ResourceManager.GetString("Equipements_AfficherRebut", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Date d&apos;achat : .
		/// </summary>
		public static string Equipements_DateAchat {
			get {
				return ResourceManager.GetString("Equipements_DateAchat", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Durée de vie : .
		/// </summary>
		public static string Equipements_DureeDeVie {
			get {
				return ResourceManager.GetString("Equipements_DureeDeVie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Fin de vie : .
		/// </summary>
		public static string Equipements_FinDeVie {
			get {
				return ResourceManager.GetString("Equipements_FinDeVie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Localisation : .
		/// </summary>
		public static string Equipements_Localisation {
			get {
				return ResourceManager.GetString("Equipements_Localisation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Modèle : .
		/// </summary>
		public static string Equipements_Modele {
			get {
				return ResourceManager.GetString("Equipements_Modele", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. équipements : .
		/// </summary>
		public static string Equipements_NbEquipements {
			get {
				return ResourceManager.GetString("Equipements_NbEquipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Numéro : .
		/// </summary>
		public static string Equipements_Numero {
			get {
				return ResourceManager.GetString("Equipements_Numero", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Date : .
		/// </summary>
		public static string GestionCampagnesVerif_Date {
			get {
				return ResourceManager.GetString("GestionCampagnesVerif_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. équipements : .
		/// </summary>
		public static string GestionCampagnesVerif_NbEquipements {
			get {
				return ResourceManager.GetString("GestionCampagnesVerif_NbEquipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Responsable : .
		/// </summary>
		public static string GestionCampagnesVerif_Responsable {
			get {
				return ResourceManager.GetString("GestionCampagnesVerif_Responsable", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à  : Attestations (pdf).
		/// </summary>
		public static string Groupe_AttestationsPdf {
			get {
				return ResourceManager.GetString("Groupe_AttestationsPdf", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à  : Effectif (Excel).
		/// </summary>
		public static string Groupe_EffectifExcel {
			get {
				return ResourceManager.GetString("Groupe_EffectifExcel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à  : Extraction des e-mails principaux.
		/// </summary>
		public static string Groupe_ExtractionsMails {
			get {
				return ResourceManager.GetString("Groupe_ExtractionsMails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Horaire : .
		/// </summary>
		public static string Groupe_Horaire {
			get {
				return ResourceManager.GetString("Groupe_Horaire", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à  à .
		/// </summary>
		public static string Groupe_HoraireSeparateur {
			get {
				return ResourceManager.GetString("Groupe_HoraireSeparateur", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Les inscriptions annulées ne seront pas prises en compte.
		/// </summary>
		public static string Groupe_InfoInscriptionsPrisesEnCompte {
			get {
				return ResourceManager.GetString("Groupe_InfoInscriptionsPrisesEnCompte", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à  : Inscriptions (pdf).
		/// </summary>
		public static string Groupe_InscriptionsPdf {
			get {
				return ResourceManager.GetString("Groupe_InscriptionsPdf", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Jour : .
		/// </summary>
		public static string Groupe_Jour {
			get {
				return ResourceManager.GetString("Groupe_Jour", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Libellé : .
		/// </summary>
		public static string Groupe_Libelle {
			get {
				return ResourceManager.GetString("Groupe_Libelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. places : .
		/// </summary>
		public static string Groupe_NbPlaces {
			get {
				return ResourceManager.GetString("Groupe_NbPlaces", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Adhérent.
		/// </summary>
		public static string Head_Adherent {
			get {
				return ResourceManager.GetString("Head_Adherent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Adresse.
		/// </summary>
		public static string Head_Adresse {
			get {
				return ResourceManager.GetString("Head_Adresse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Catégorie.
		/// </summary>
		public static string Head_Categorie {
			get {
				return ResourceManager.GetString("Head_Categorie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Contact.
		/// </summary>
		public static string Head_Contact {
			get {
				return ResourceManager.GetString("Head_Contact", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Déplacer les équipements sélectionnés.
		/// </summary>
		public static string Head_DeplacerEquipements {
			get {
				return ResourceManager.GetString("Head_DeplacerEquipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Divers.
		/// </summary>
		public static string Head_Divers {
			get {
				return ResourceManager.GetString("Head_Divers", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Dossier.
		/// </summary>
		public static string Head_Dossier {
			get {
				return ResourceManager.GetString("Head_Dossier", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Durée de vie.
		/// </summary>
		public static string Head_DureeDeVie {
			get {
				return ResourceManager.GetString("Head_DureeDeVie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Equipement.
		/// </summary>
		public static string Head_Equipement {
			get {
				return ResourceManager.GetString("Head_Equipement", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Pour les équipements sélectionnés.
		/// </summary>
		public static string Head_EquipementsSelectionnes {
			get {
				return ResourceManager.GetString("Head_EquipementsSelectionnes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Identité.
		/// </summary>
		public static string Head_Identité {
			get {
				return ResourceManager.GetString("Head_Identité", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Informations.
		/// </summary>
		public static string Head_Informations {
			get {
				return ResourceManager.GetString("Head_Informations", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Inscription.
		/// </summary>
		public static string Head_Inscription {
			get {
				return ResourceManager.GetString("Head_Inscription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Localisation.
		/// </summary>
		public static string Head_Localisation {
			get {
				return ResourceManager.GetString("Head_Localisation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Marque.
		/// </summary>
		public static string Head_Marque {
			get {
				return ResourceManager.GetString("Head_Marque", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Modèle.
		/// </summary>
		public static string Head_Modele {
			get {
				return ResourceManager.GetString("Head_Modele", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Options.
		/// </summary>
		public static string Head_Options {
			get {
				return ResourceManager.GetString("Head_Options", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Outils.
		/// </summary>
		public static string Head_Outils {
			get {
				return ResourceManager.GetString("Head_Outils", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Outils globaux.
		/// </summary>
		public static string Head_OutilsGlobaux {
			get {
				return ResourceManager.GetString("Head_OutilsGlobaux", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Outils groupe.
		/// </summary>
		public static string Head_OutilsGroupe {
			get {
				return ResourceManager.GetString("Head_OutilsGroupe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Saison.
		/// </summary>
		public static string Head_Saison {
			get {
				return ResourceManager.GetString("Head_Saison", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Section.
		/// </summary>
		public static string Head_Section {
			get {
				return ResourceManager.GetString("Head_Section", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Stats.
		/// </summary>
		public static string Head_Stats {
			get {
				return ResourceManager.GetString("Head_Stats", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion des tranches d&apos;âge.
		/// </summary>
		public static string Head_TranchesAge {
			get {
				return ResourceManager.GetString("Head_TranchesAge", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ville.
		/// </summary>
		public static string Head_Ville {
			get {
				return ResourceManager.GetString("Head_Ville", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Adresse : .
		/// </summary>
		public static string InfosClub_Adresse {
			get {
				return ResourceManager.GetString("InfosClub_Adresse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Mail : .
		/// </summary>
		public static string InfosClub_Mail {
			get {
				return ResourceManager.GetString("InfosClub_Mail", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nom du club : .
		/// </summary>
		public static string InfosClub_Nom {
			get {
				return ResourceManager.GetString("InfosClub_Nom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à N° établissement APS : .
		/// </summary>
		public static string InfosClub_NumAps {
			get {
				return ResourceManager.GetString("InfosClub_NumAps", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à N° association : .
		/// </summary>
		public static string InfosClub_NumAssociation {
			get {
				return ResourceManager.GetString("InfosClub_NumAssociation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à N° affiliation : .
		/// </summary>
		public static string InfosClub_NumFederation {
			get {
				return ResourceManager.GetString("InfosClub_NumFederation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à SIRET : .
		/// </summary>
		public static string InfosClub_Siret {
			get {
				return ResourceManager.GetString("InfosClub_Siret", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Web : .
		/// </summary>
		public static string InfosClub_SiteWeb {
			get {
				return ResourceManager.GetString("InfosClub_SiteWeb", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Tél. : .
		/// </summary>
		public static string InfosClub_Telephone {
			get {
				return ResourceManager.GetString("InfosClub_Telephone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ville : .
		/// </summary>
		public static string InfosClub_Ville {
			get {
				return ResourceManager.GetString("InfosClub_Ville", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Adresse : .
		/// </summary>
		public static string InitDb_AdresseClub {
			get {
				return ResourceManager.GetString("InitDb_AdresseClub", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nom du club : .
		/// </summary>
		public static string InitDb_NomClub {
			get {
				return ResourceManager.GetString("InitDb_NomClub", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ville : .
		/// </summary>
		public static string InitDb_VilleClub {
			get {
				return ResourceManager.GetString("InitDb_VilleClub", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Veuillez renseigner le(s) champ(s) ci-dessous afin d&apos;initialiser la base pour une première utilisation..
		/// </summary>
		public static string InitiDB_Explications {
			get {
				return ResourceManager.GetString("InitiDB_Explications", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Certificat médical : .
		/// </summary>
		public static string Inscription_CertificatMedical {
			get {
				return ResourceManager.GetString("Inscription_CertificatMedical", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Cotisation : .
		/// </summary>
		public static string Inscription_Cotisation {
			get {
				return ResourceManager.GetString("Inscription_Cotisation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Groupe : .
		/// </summary>
		public static string Inscription_Groupe {
			get {
				return ResourceManager.GetString("Inscription_Groupe", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Montant : .
		/// </summary>
		public static string Inscription_MontantLicence {
			get {
				return ResourceManager.GetString("Inscription_MontantLicence", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. inscriptions : .
		/// </summary>
		public static string Inscription_NbInscriptions {
			get {
				return ResourceManager.GetString("Inscription_NbInscriptions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Licence : .
		/// </summary>
		public static string Inscription_NumLicence {
			get {
				return ResourceManager.GetString("Inscription_NumLicence", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Saison : .
		/// </summary>
		public static string Inscription_Saison {
			get {
				return ResourceManager.GetString("Inscription_Saison", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Section : .
		/// </summary>
		public static string Inscription_Section {
			get {
				return ResourceManager.GetString("Inscription_Section", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Statut : .
		/// </summary>
		public static string Inscription_Statut {
			get {
				return ResourceManager.GetString("Inscription_Statut", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Date de création : .
		/// </summary>
		public static string Label_DateCreation {
			get {
				return ResourceManager.GetString("Label_DateCreation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Date de modification : .
		/// </summary>
		public static string Label_DateModification {
			get {
				return ResourceManager.GetString("Label_DateModification", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Libellé : .
		/// </summary>
		public static string Localisation_Libelle {
			get {
				return ResourceManager.GetString("Localisation_Libelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. localisations : .
		/// </summary>
		public static string Localisation_NbLocalisations {
			get {
				return ResourceManager.GetString("Localisation_NbLocalisations", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Activer le chargement automatique de la dernière base utilisée.
		/// </summary>
		public static string MainScreen_ActiverChargementAuto {
			get {
				return ResourceManager.GetString("MainScreen_ActiverChargementAuto", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Aucune chaîne de connexion n&apos;est enregistrée.
		/// </summary>
		public static string MainScreen_AucuneChaineDeConnexion {
			get {
				return ResourceManager.GetString("MainScreen_AucuneChaineDeConnexion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Libellé : .
		/// </summary>
		public static string Marque_Libelle {
			get {
				return ResourceManager.GetString("Marque_Libelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. marques : .
		/// </summary>
		public static string Marques_NbMarques {
			get {
				return ResourceManager.GetString("Marques_NbMarques", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Adhérents.
		/// </summary>
		public static string Menu_Adherents {
			get {
				return ResourceManager.GetString("Menu_Adherents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à A propos.
		/// </summary>
		public static string Menu_APropos {
			get {
				return ResourceManager.GetString("Menu_APropos", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Catégories.
		/// </summary>
		public static string Menu_Categories {
			get {
				return ResourceManager.GetString("Menu_Categories", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à CNIL.
		/// </summary>
		public static string Menu_CNIL {
			get {
				return ResourceManager.GetString("Menu_CNIL", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ecran de démarrage.
		/// </summary>
		public static string Menu_Demarrage {
			get {
				return ResourceManager.GetString("Menu_Demarrage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Durées de vie.
		/// </summary>
		public static string Menu_DureesDeVie {
			get {
				return ResourceManager.GetString("Menu_DureesDeVie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Equipements.
		/// </summary>
		public static string Menu_Equipements {
			get {
				return ResourceManager.GetString("Menu_Equipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Graphiques.
		/// </summary>
		public static string Menu_Graphiques {
			get {
				return ResourceManager.GetString("Menu_Graphiques", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Groupes.
		/// </summary>
		public static string Menu_Groupes {
			get {
				return ResourceManager.GetString("Menu_Groupes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Infos du club.
		/// </summary>
		public static string Menu_InfosClub {
			get {
				return ResourceManager.GetString("Menu_InfosClub", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Inscriptions.
		/// </summary>
		public static string Menu_Inscriptions {
			get {
				return ResourceManager.GetString("Menu_Inscriptions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Localisations.
		/// </summary>
		public static string Menu_Localisations {
			get {
				return ResourceManager.GetString("Menu_Localisations", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Marques.
		/// </summary>
		public static string Menu_Marques {
			get {
				return ResourceManager.GetString("Menu_Marques", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Modèles.
		/// </summary>
		public static string Menu_Modeles {
			get {
				return ResourceManager.GetString("Menu_Modeles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Quitter.
		/// </summary>
		public static string Menu_Quitter {
			get {
				return ResourceManager.GetString("Menu_Quitter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Rapports.
		/// </summary>
		public static string Menu_Rapports {
			get {
				return ResourceManager.GetString("Menu_Rapports", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Saisons.
		/// </summary>
		public static string Menu_Saisons {
			get {
				return ResourceManager.GetString("Menu_Saisons", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Sauvegardes.
		/// </summary>
		public static string Menu_Sauvegardes {
			get {
				return ResourceManager.GetString("Menu_Sauvegardes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Sections.
		/// </summary>
		public static string Menu_Sections {
			get {
				return ResourceManager.GetString("Menu_Sections", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Tranches d&apos;âge.
		/// </summary>
		public static string Menu_TranchesAge {
			get {
				return ResourceManager.GetString("Menu_TranchesAge", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Vérifications.
		/// </summary>
		public static string Menu_Verifications {
			get {
				return ResourceManager.GetString("Menu_Verifications", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Villes.
		/// </summary>
		public static string Menu_Villes {
			get {
				return ResourceManager.GetString("Menu_Villes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Catégories : .
		/// </summary>
		public static string Modeles_Categorie {
			get {
				return ResourceManager.GetString("Modeles_Categorie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Couleur 1 : .
		/// </summary>
		public static string Modeles_Couleur1 {
			get {
				return ResourceManager.GetString("Modeles_Couleur1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Couleur 2 : .
		/// </summary>
		public static string Modeles_Couleur2 {
			get {
				return ResourceManager.GetString("Modeles_Couleur2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Couleur 3 : .
		/// </summary>
		public static string Modeles_Couleur3 {
			get {
				return ResourceManager.GetString("Modeles_Couleur3", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Marque : .
		/// </summary>
		public static string Modeles_Marque {
			get {
				return ResourceManager.GetString("Modeles_Marque", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. modèles : .
		/// </summary>
		public static string Modeles_NbModeles {
			get {
				return ResourceManager.GetString("Modeles_NbModeles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nom : .
		/// </summary>
		public static string Modeles_Nom {
			get {
				return ResourceManager.GetString("Modeles_Nom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Retour.
		/// </summary>
		public static string SaisiesVerifications_Retour {
			get {
				return ResourceManager.GetString("SaisiesVerifications_Retour", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Valider la campagne.
		/// </summary>
		public static string SaisiesVerifications_ValiderCampagne {
			get {
				return ResourceManager.GetString("SaisiesVerifications_ValiderCampagne", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Année de début : .
		/// </summary>
		public static string Saison_AnneeDebut {
			get {
				return ResourceManager.GetString("Saison_AnneeDebut", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. saisons : .
		/// </summary>
		public static string Saisons_NbSaisons {
			get {
				return ResourceManager.GetString("Saisons_NbSaisons", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Libellé : .
		/// </summary>
		public static string Section_Libelle {
			get {
				return ResourceManager.GetString("Section_Libelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. sections : .
		/// </summary>
		public static string Section_NbSections {
			get {
				return ResourceManager.GetString("Section_NbSections", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Equipements.
		/// </summary>
		public static string TabMenu_Equipements {
			get {
				return ResourceManager.GetString("TabMenu_Equipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Inscriptions.
		/// </summary>
		public static string TabMenu_Inscriptions {
			get {
				return ResourceManager.GetString("TabMenu_Inscriptions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Menu.
		/// </summary>
		public static string TabMenu_Menu {
			get {
				return ResourceManager.GetString("TabMenu_Menu", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Outils.
		/// </summary>
		public static string TabMenu_Outils {
			get {
				return ResourceManager.GetString("TabMenu_Outils", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Référentiel.
		/// </summary>
		public static string TabMenu_Referentiel {
			get {
				return ResourceManager.GetString("TabMenu_Referentiel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Ajouter une ville.
		/// </summary>
		public static string Tltp_AjouterVille {
			get {
				return ResourceManager.GetString("Tltp_AjouterVille", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Changer le statut.
		/// </summary>
		public static string Tltp_ChangerStatut {
			get {
				return ResourceManager.GetString("Tltp_ChangerStatut", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Cliquer pour passer le statut à &apos;Non remis&apos;.
		/// </summary>
		public static string Tltp_ChangeStatutCertificatNonRemis {
			get {
				return ResourceManager.GetString("Tltp_ChangeStatutCertificatNonRemis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Cliquer pour passer le statut à &apos;Remis&apos;.
		/// </summary>
		public static string Tltp_ChangeStatutCertificatRemis {
			get {
				return ResourceManager.GetString("Tltp_ChangeStatutCertificatRemis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Inscrire/Voir l&apos;incription.
		/// </summary>
		public static string Tltp_CreerVoirInscription {
			get {
				return ResourceManager.GetString("Tltp_CreerVoirInscription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Déplacer.
		/// </summary>
		public static string Tltp_Deplacer {
			get {
				return ResourceManager.GetString("Tltp_Deplacer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Attestation (pdf).
		/// </summary>
		public static string Tltp_Document_AttestationPdf {
			get {
				return ResourceManager.GetString("Tltp_Document_AttestationPdf", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Fiche inscription (pdf).
		/// </summary>
		public static string Tltp_DocumentInscriptionPdf {
			get {
				return ResourceManager.GetString("Tltp_DocumentInscriptionPdf", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Attestation d&apos;inscriptions du groupe (pdf).
		/// </summary>
		public static string Tltp_DocumentsGroupe_AttestationsPdf {
			get {
				return ResourceManager.GetString("Tltp_DocumentsGroupe_AttestationsPdf", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Fiches inscriptions du groupe (pdf).
		/// </summary>
		public static string Tltp_DocumentsGroupe_InscriptionsPdf {
			get {
				return ResourceManager.GetString("Tltp_DocumentsGroupe_InscriptionsPdf", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Dupliquer cet adhérent.
		/// </summary>
		public static string Tltp_DupliquerAdherent {
			get {
				return ResourceManager.GetString("Tltp_DupliquerAdherent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Génération du rapport d&apos;effectif (Excel).
		/// </summary>
		public static string Tltp_EffectifExcel {
			get {
				return ResourceManager.GetString("Tltp_EffectifExcel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Enregistrer.
		/// </summary>
		public static string Tltp_Enregistrer {
			get {
				return ResourceManager.GetString("Tltp_Enregistrer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Extraction des e-mails principaux.
		/// </summary>
		public static string Tltp_ExtractionEmails {
			get {
				return ResourceManager.GetString("Tltp_ExtractionEmails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Gestion de la localisation des équipements.
		/// </summary>
		public static string Tltp_LocalisationEquipements {
			get {
				return ResourceManager.GetString("Tltp_LocalisationEquipements", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à NIC.
		/// </summary>
		public static string Tltp_NIC {
			get {
				return ResourceManager.GetString("Tltp_NIC", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Vie de l&apos;équipement sélectionné (Excel).
		/// </summary>
		public static string Tltp_ReportVieEquipement {
			get {
				return ResourceManager.GetString("Tltp_ReportVieEquipement", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Saisir les vérifications.
		/// </summary>
		public static string Tltp_SaisirVerifications {
			get {
				return ResourceManager.GetString("Tltp_SaisirVerifications", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Afficher la fiche de l&apos;adhérent.
		/// </summary>
		public static string Tltp_ShowDetailsAdherent {
			get {
				return ResourceManager.GetString("Tltp_ShowDetailsAdherent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à SIREN.
		/// </summary>
		public static string Tltp_Siren {
			get {
				return ResourceManager.GetString("Tltp_Siren", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Age de début (inclus) : .
		/// </summary>
		public static string TranchesAge_AgeInf {
			get {
				return ResourceManager.GetString("TranchesAge_AgeInf", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Age de fin (inclus) : .
		/// </summary>
		public static string TranchesAge_AgeSup {
			get {
				return ResourceManager.GetString("TranchesAge_AgeSup", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. tranches d&apos;âge : .
		/// </summary>
		public static string TranchesAge_NbTranches {
			get {
				return ResourceManager.GetString("TranchesAge_NbTranches", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Code postal : .
		/// </summary>
		public static string Ville_CodePostal {
			get {
				return ResourceManager.GetString("Ville_CodePostal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Libellé : .
		/// </summary>
		public static string Ville_Libelle {
			get {
				return ResourceManager.GetString("Ville_Libelle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Nb. villes : .
		/// </summary>
		public static string Ville_NbVilles {
			get {
				return ResourceManager.GetString("Ville_NbVilles", resourceCulture);
			}
		}
	}
}
